services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: platform_db
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platform"]
      interval: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/platform_db
      KC_DB_USERNAME: platform
      KC_DB_PASSWORD: platform123
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres

volumes:
  pgdata:
