server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db
    username: platform
    password: platform123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt-expiry-minutes: 15
