server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/platform_db
    username: platform
    password: platform123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt-secret: ThisIsAVeryLongSecretKeyForPlatformMonolithThatIsAtLeast64CharsLong123!
  jwt-expiry-minutes: 60
  default-tenant: default

logging:
  level:
    com.platform: DEBUG
    org.springframework.security: INFO
